//create student
POST http://localhost:5000/api/student
Content-Type: application/json

{
    "fullName": "Minh",
    "studentImage": [
        
    ],
    "enrollmentNo": "abc", 
    "studentId": "abc"
}

//delete student
###
DELETE  http://localhost:5000/api/student/61bdf040677b98012ee0c1f7

###
//get all classes
GET http://localhost:5000/api/class

###
//create class
POST http://localhost:5000/api/class
Content-Type: application/json

{
    "className": "Lap trinh nang cao",
    "subjectId": "123",
    "lecturerId": "61e12142ca2d87106040019c",
    "startDate": "06/12/2021",
    "endDate" : "06/12/2023",
    "startTime" : "0",
    "endTime": "24",
    "dayOfWeek": "3",
    "students": ["1811050277","1811063256"]
}

//get all attendance
###
GET http://localhost:5000/api/attendance/

###
//get attendance by class id
POST http://localhost:5000/api/attendance/getClassAttendance
Content-Type: application/json

{
    "classId": "61e1223eeb5fcae51564a7c9"
}

###
//create attendance
POST http://localhost:5000/api/attendance/createAttendance
Content-Type: application/json

{
    "studentId": "1811050277",
    "studentName" : "NguyenNhatMinh"
    "classId": "61df990dc4c5681fd6cb7c22"
}

###
//attending
POST http://localhost:5000/api/attendance/pushAttendance
Content-Type: application/json

{
    "studentId": "1811050277",
    "classId": "61df94eeb5af3a9cc714fd2a"
}

###
//get all teachers
GET http://localhost:5000/api/teacher


###
//login teacher
POST http://localhost:5000/api/teacher/login
Content-Type: application/json

{
    "username": "congnhut_hutech",
    "password": "123456"
}


###
//create teacher
POST http://localhost:5000/api/teacher/register
Content-Type: application/json

{
    "username": "congnhut_hutech",
    "password": "123456",
    "teacherName": "Trinh Cong Nhut"
}


//find teaching classes by teacher id
###
GET http://localhost:5000/api/teacher/teacherClasses
Content-Type: application/json

{
    "teacherid": "61e12142ca2d87106040019c"
}

//find class by id
###
GET http://localhost:5000/api/class/findclass
Content-Type: application/json

{
    "_id": "61e1223eeb5fcae51564a7c9"
}


###
//register customer
POST http://localhost:5000/api/customer/register
Content-Type: application/json

{
    "username": "0946294394",
    "password": "123456",
    "fullName": "Nguyen Nhat Minh"
}

###
//create new drinks
POST http://localhost:5000/api/drink/
Content-Type: application/json

{
    "drinkName": "PHINDI CHOCO",
    "defaultPrice": 49000,
    "description": "PhinDi Choco - Cà phê Phin thế hệ mới với chất Phin êm hơn, kết hợp cùng Choco ngọt tan mang đến hương vị mới lạ, không thể hấp dẫn hơn!"
}

###
//get drinks
GET http://localhost:5000/api/drinks/

###
//get drinks by caetory
GET http://localhost:5000/api/drinks/findbycategory
Content-Type: application/json

{
    "category": "COFFEE"
}
