export const apiUrl = 'http://localhost:5000'

export const GET_INCOME_REPORT = 'GET_INCOME_REPORT'
export const GET_INCOME_REPORT_BY_FILTER = 'GET_INCOME_REPORT_BY_FILTER'
export const GET_PRODUCTS_REPORT = 'GET_INCOMES_REPORT'
export const GET_ORDERS_REPORT = 'GET_ORDERS_REPORT'
export const GET_CUSTOMERS_REPORT = 'GET_CUSTOMERS_REPORT'
export const GET_USERS_REPORT = 'GET_USERS_REPORT'
export const GET_COUPONS_REPORT = 'GET_COUPONS_REPORT'
export const SEARCH_PRODUCTS = 'SEARCH_PRODUCTS'

export const SET_AUTH = 'SET_AUTH'
export const LOCAL_STORAGE_TOKEN_NAME = 'admin-coffeeshop'